Description: >
  Setup Prometheus
Resources:
  PrometheusSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Setup Prometheus.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0
      
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups: [!Ref PrometheusSG]
      KeyName: Udacity_keyPair
      ImageId: ami-007855ac798b5175e
      Tags:
        - Key: Name
          Value: UdaPeople-Prometheus
  
  PrometheusEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
